### ISSUE TITLE
Need to obtain tRF targets for tRF sequences that are not present in tRF database

### ISSUE THREAD

**Issue by Candida05** [ZWang-Lab/tRFtarget#1] opened 2021-07-05 10:10 UTC
Dear tRF target developers,

I am very interested in your database as I have a set of tRF sequences from human sperm that are not present in the tRF database and so I do not have the required tRF IDs (eg: tRF-1001). I am very keen to get the targets from your database, please advise.

Thanks & Best wishes,
Candida

**Comment by az7jh2** [comment] 2021-07-06 20:57
Hi @Candida05 

Thanks for reporting it to us. We understand you have some tRF sequences which are not indexed in our database. Based on whether these tRF sequences are publicashed, we can provide the target genes for unindexed tRFs in two ways:

1. If these tRF sequences are published, then can you point out the reference? We can download these tRF sequences and add them to our database.
2. If these tRF sequences are not published, then we can either provide a pipeline which can be run in your computer, or add a new feature in our web page to allow user to upload unindexed tRF sequences and get target genes. 

Can you give us more information about it? Thanks!

**Comment by Candida05** [comment] 2021-07-08 04:21
Dear tRF target developers,

Thank you so much for your prompt reply. 
Our tRF sequences are not yet published as our manuscript is in communication. 

It would be very helpful as you mentioned: 
if you can either provide a pipeline which can be run on user's computer or if you can add in a new feature on your web page to allow the user to upload unindexed tRF sequences and get target genes.

We have been trying hard to get the functionality of our tRF sequences and your tRF target pipeline can help us add value to our paper. We would be very grateful for this and will cite your tool in our paper. Once our paper is published, you can also add in our tRF sequences to your database.

Looking forward to your reply.

Best wishes,
Candida

**Comment by az7jh2** [comment] 2021-07-08 13:51
Hi @Candida05.

Now I understand your request. Since the updating of web site will last a long time, so I think the easiest and fastest way would be providing a Docker image for you to run our pipeline in your local computer.

I will begin to create the Docker image, and publish it as soon as possible. If you don't mind, I will let this issue open, and once I publish the Docker image, I will let you know.

**Comment by Candida05** [comment] 2021-07-09 01:30
Dear tRF target pipeline developers,

Thank you so much for your prompt reply and help. Looking forward to receiving the Docker image for running the pipeline
 on our computer. 
Best wishes!

**Comment by Candida05** [comment] 2021-07-19 05:17
Dear tRF target pipeline developers,

Thanks so much for your offer to help with the Docker image. Please let me know when will it be published. 
Looking forward to it!

Best wishes,
Candida

**Comment by az7jh2** [comment] 2021-07-19 13:58
Hi @Candida05 

Thanks for your patience. We are now developing the Docker image and I want to tell you this is now the highest priority.

We will publish a simple version first, and later will include more features in the Docker image in the feature updates.

So I think we can publish this first version of Docker image by the end of July. I will keep you posted.

Thanks again for your patience!

**Comment by Candida05** [comment] 2021-07-19 23:42
Thank you so much for your kind help and support! 

Appreciate your efforts!

**Comment by az7jh2** [comment] 2021-07-30 19:52
Hi. @Candida05 

Thank you for your interest in trying our database tool. I appreciate your patience. Currently I’m fully occupied by one of my projects and a grant proposal that is due in a month. As I’m new to developing Docker images, it takes much longer time for me to prepare and publish our pipeline Docker file than what I expected. I am so sorry that the docker file won't be ready in a short time period. But I’m happy to help if you need the results sooner.


Here are two options we may consider:

1. If you don't mind to send me your tRF sequence, I will help run the pipeline on my side and generate the target gene list for you. It's much easier for me to run the pipeline which is already available than to develop a whole Docker image. I understand that this is unpublished sequence and I will keep it confidential.

2. If you don’t mind to wait for me to publish the pipeline Docker file, I will keep you posted. Based on my current timeline, I expect the Docker file will be available around the end of September/early October.


Thank you for considering.

**Comment by Candida05** [comment] 2021-08-02 07:11
No worries, I understand. 
I will let you know if I can send you the sequences. Will check with my Lab's Principal Investigator. 
Will also look forward to the Docker file, whenever it is ready. 

Thanks a ton!
Candida

**Comment by az7jh2** [comment] 2021-08-02 13:50
Thank you for the understanding! I will keep you posted. When the Docker image file is ready, I will let you know.

**Comment by Candida05** [comment] 2021-08-24 04:11
Dear ZWang-Lab/tRF target tool developers,

Hope you are doing well!

As you mentioned that you could run the pipeline at your side and send the target results to me, I am sending you few sequences for tRF target prediction. Could you send me the top target genes from your tool along with the GO results. Could you mail the results to ***@***.******@***.***>

I will be really grateful for your time and effort. Will continue to look forward to receiving the Docker file whenever it is ready. Please take your time. All the best for your grant submission!

Thanks & Best wishes,
Candida

**Comment by az7jh2** [comment] 2021-08-25 14:07
Hi @Candida05 

Thanks for your understanding. You can send the tRF sequences and emails for recieving results to my email ningshan.li@yale.edu. Please DO NOT post that information here. And I will keep all those information confidential.

As designed in our pipeline, it will return predicted target genes, and you can select the top target genes by whatever threshold. And it only contain the ENST and ENSG ID, so I am afraid you need to map the gene ID to Go term by yourself. 

If anything I can help,  please feel free to let me know.

**Comment by az7jh2** [comment] 2021-10-31 08:36
Hi @Candida05 

Thanks for your patience. We appreciate it.

We are glad to announce that our pipeline is available now! please refer our GitHub repo [tRFtarget-pipeline](https://github.com/ZWang-Lab/tRFtarget-pipeline) for detailed information.

If you don't mind, I will close this issue. For issues in running our pipeline, please report issues in that pipeline repo.

Thanks!

**Comment by Candida05** [comment] 2021-11-05 12:22
Dear tRF Target pipeline developers,

Thank you so much for making the pipeline available! This is very helpful!

Yes please close the issue.

Thanks & Best wishes,
Candida Vaz

**Closed** 2021-11-06 01:43 UTC
Labels: enhancement
